language: node_js
node_js:
  - "6"
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_b5d1c3ab6ab4_key -iv $encrypted_b5d1c3ab6ab4_iv -in config/firebase/secrets.tar.enc -out config/firebase/secrets.tar -d
  - tar xvf config/firebase/secrets.tar
script:
  - npm run preflight
after_success:
  - npm run build:integration
  - ./node_modules/.bin/firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD} -P integration