language: node_js
node_js:
  - "6"
branches:
  only:
    - develop
    - master
    - /^release/
cache: yarn
before_install:
  - openssl aes-256-cbc -K $encrypted_b5d1c3ab6ab4_key -iv $encrypted_b5d1c3ab6ab4_iv -in config/firebase/secrets.tar.enc -out config/firebase/secrets.tar -d
  - tar xvf config/firebase/secrets.tar
script:
  - npm run preflight
after_success:
  - export DEPLOY_TARGET="staging" # Catch /^release/ branches as the base case to avoid regexes.
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then export DEPLOY_TARGET="integration"; fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then export DEPLOY_TARGET="production"; fi
  - scripts/deploy.sh $DEPLOY_TARGET