export const AUTH_STATUS_UPDATED = 'AUTH_STATUS_UPDATED';
export const AUTH_STATUS_READY = 'AUTH_STATUS_READY';
export const AUTH_COMMAND_COMPLETED = 'AUTH_COMMAND_COMPLETED';
export const AUTH_COMMAND_NEXT_PATH = 'AUTH_COMMAND_NEXT_PATH';
export const AUTH_COMMAND = 'AUTH_COMMAND';